### ISSUE TITLE
Setup status page to monitor outages

### ISSUE THREAD

**Issue by pke** [milgner/keedrop#29]
This service should run on a different server.
Evaluate existing solutions that are free for open source projects.

**Comment by milgner** [comment]
They have monitor-specific API keys and it looks like this should work: https://uptimerobot.com/api

**Comment by milgner** [comment]
It's there: https://stats.uptimerobot.com/JEGW7u8QAv
I also set up a `CNAME` record for `status.keedrop.com`, it should become available in a bit.

Right now it sends mail to my personal mail account as well as a webhook to OpsGenie which will deliver a SMS message.
