### ISSUE TITLE
Fill in imprint from environment variables

### ISSUE THREAD

**Issue by milgner** [milgner/keedrop#32]
Just in case someone wants to deploy it on their own server, it shouldn't have my imprint in there :sweat_smile:

**Comment by pke** [comment]
Could this also be done via a second config file?

**Comment by milgner** [comment]
It would need to be a mechanism that can be configured during CI and not checked into version control. Right now, environment variables are the only thing I could think of...

**Comment by pke** [comment]
Couldn't the rakefile write the additional config based on env vars?

**Comment by pke** [comment]
or maybe we can modify this simple GEM

https://github.com/iBug/jekyll-environment-variables/blob/master/lib/jekyll-environment-variables.rb

to override `site` config via env vars following the pattern:

```yaml
contact:
  name: Your Name
```

```export JEKYLL_CONFIG_CONTACT_NAME=My Name```

**Comment by milgner** [comment]
That does sound like a plan, yes. I'll look into it 👍
