### ISSUE TITLE
Remove references to cors-anywhere

### ISSUE THREAD

**Issue by milgner** [milgner/keedrop#39]
The server has a proper CORS policy.

**Comment by pke** [comment]
Hmmm this of course makes local testing impossible, since the CORS header do not include localhost as origin?

**Comment by milgner** [comment]
Hmm... What about a fake API for testing purposes? Alternatively we could have a staging system that also allows `localhost` - but I am not sure that I want to maintain a staging system for  a small pet project, too... 🤔
Maybe an OpenAPI spec would help as there are many tools around that can spin up fake servers for them.

**Comment by pke** [comment]
I'll do a conditional script include in `_layout/default.html` which will argument the API URL base on ENV var `JEKYLL_CONFIG_API_HOSTNAME`
